### PR TITLE
Fix slowness in delegate page

### LINKED ISSUE #151: Something is super slow when clicking on delegate..
the time between the click, and the loader is just too long on a delegate page. There's something fishy and we need to find out bc it makes the experience not great.

### PR DESCRIPTION
**Pull request by Tbaut**
closes #151

### CODE REVIEW

**Comment by Tbaut** [comment]
The main issue was
- rendering of the modal even when not needed
- many complex functions re-rendering, the heaviest was `isExhaustedRessources`

If you type in the input now, it's instant. Before it took a sec for the text to appear.

File: src/header.tsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ import { ConnectionDialog } from 'dot-connect/react.js'
 //   MenubarTrigger,
 // } from '@/components/ui/menubar'
 import { useAccounts } from './contexts/AccountsContext'
-import { useEffect, useState } from 'react'
+import React, { useEffect, useState } from 'react'
```
Comment (wirednkod) [inline src/header.tsx:26]: lets keep it simple:
```suggestion
import { Fragment, useEffect, useState } from 'react'
```

File: src/header.tsx [hunk 2]
```diff
@@ -189,7 +189,7 @@ export const Header = () => {
                 </DropdownMenuTrigger>
                 <DropdownMenuContent className="max-h-[calc(100vh-5rem)] overflow-auto">
                   {accounts.map((account, index) => (
-                    <>
+                    <React.Fragment key={account.address}>
```
Comment (wirednkod) [inline src/header.tsx:192]:
```suggestion
                    <Fragment key={account.address}>
```

File: src/header.tsx [hunk 3]
```diff
@@ -206,7 +206,7 @@ export const Header = () => {
                       {index !== accounts.length - 1 && (
                         <DropdownMenuSeparator />
                       )}
-                    </>
+                    </React.Fragment>
```
Comment (wirednkod) [inline src/header.tsx:209]:
```suggestion
                    </Fragment>
```

File: src/hooks/useTestTx.tsx [hunk 4]
```diff
@@ -7,18 +7,20 @@ import {
...
+    () =>
+      sr25519CreateDerive(entropyToMiniSecret(mnemonicToEntropy(DEV_PHRASE))),
+    [],
   )
-  const aliceKeyPair = derive('//Alice')
-  const aliceSigner = getPolkadotSigner(
-    aliceKeyPair.publicKey,
-    'Sr25519',
-    aliceKeyPair.sign,
+  const aliceKeyPair = useMemo(() => derive('//Alice'), [derive])
```
Comment (wirednkod) [inline src/hooks/useTestTx.tsx:19]: Not sure I understand this... derive (line 14) already uses `useMemo`. Why to reuse it?

File: src/pages/Delegate/index.tsx [hunk 5]
```diff
@@ -66,7 +114,12 @@ export const Delegate = () => {
   }, [address, delegate, getDelegateByAddress, isLoadingDelegates])
 
   const { display: convictionTimeDisplay, multiplier: convictionMultiplier } =
-    getConvictionLockTimeDisplay(convictionNo)
+    useMemo(() => {
+      return (
+        getConvictionLockTimeDisplay(convictionNo) ||
+        getConvictionLockTimeDisplay(convictionNo)
+      )
+    }, [convictionNo, getConvictionLockTimeDisplay])
```
Comment (wirednkod) [inline src/pages/Delegate/index.tsx:122]:
```suggestion
    useMemo(() => (
      getConvictionLockTimeDisplay(convictionNo) ||
      getConvictionLockTimeDisplay(convictionNo)
    ), [convictionNo, getConvictionLockTimeDisplay])
```

File: src/pages/Delegate/index.tsx [hunk 6]
```diff
@@ -101,77 +154,67 @@ export const Delegate = () => {
...
+      .then((tracks) => {
+        const trackIds = tracks.map(([track]) => track)
+        setAllTracks(trackIds)
+      })
+      .catch(console.error)
+  }, [api])
+
+  const onChangeAmount = useCallback(
+    (e: React.ChangeEvent<HTMLInputElement>) => {
+      console.log('e.target.value', e.target.value)
```
Comment (wirednkod) [inline src/pages/Delegate/index.tsx:170]: is this needed?

File: src/pages/Delegate/index.tsx [hunk 7]
```diff
@@ -101,77 +154,67 @@ export const Delegate = () => {
...
+      const [bnResult, errorMessage] = evalUnits(
+        e.target.value,
+        assetInfo.precision,
+      )
+      setAmount(bnResult || 0n)
+      if (errorMessage) setAmountError(errorMessage)
+      setAmountVisible(e.target.value)
+      const date2 = new Date()
+      const diff = date2.getTime() - date1.getTime()
+      console.log('date2 - date1', diff)
```
Comment (wirednkod) [inline src/pages/Delegate/index.tsx:183]: is this needed?

**Review by wirednkod — CHANGES_REQUESTED** [review]

File: src/hooks/useTestTx.tsx (hunk 4 above)
Comment (Tbaut) [reply src/hooks/useTestTx.tsx:19]: Because we don't need to derive every single render if `derive` doesn't change. So thie `aliceKeyPair` will be derived once for all. Also I just memoize / useCallback everything at this point. Spending an hour to find the one function that makes everything slow is more time consuming than bluntly memoizing every single const IMHO. I used to do this in all my apps, chose not to be annoying for Delegit, and it bit us all the same. The experience of using the delegate page just got much much better thanks to this.

File: src/pages/Delegate/index.tsx (hunk 6 above)
Comment (Tbaut) [reply src/pages/Delegate/index.tsx:170]: absolutely not. Thanks

File: src/pages/Delegate/index.tsx (hunk 7 above)
Comment (Tbaut) [reply src/pages/Delegate/index.tsx:183]: absolutely not. Thanks

**Comment by Tbaut** [comment]
Thanks for the review, and sorry for the 1000 oversights of logs etc :sweat_smile:

**Review by wirednkod — APPROVED** [review]
