### PR TITLE
Fix long list

### LINKED ISSUE #97: Group delegations by amount and conviction
see https://github.com/delegit-xyz/dashboard/pull/89#issuecomment-2328136651

### PR DESCRIPTION
**Pull request by Tbaut**
closes #97 

Tested heavily, as can be seen here. Different conviction or amount are on 2 lines, the others are grouped

https://github.com/user-attachments/assets/5d8eed35-73fe-480d-8b3f-2e4285c94750

---

Submission checklist:

#### Layout

- [x] Change inspected in the mobile web ui
- [x] Change inspected in dark mode

### CODE REVIEW

File: src/components/DelegationByAmountConviction.tsx [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+  amountConvictionMap: Record<string, CurrentDelegation[]>
+}
+
+const TrackDisplay = ({
+  trackId,
+  trackName,
+}: {
+  trackId: number
+  trackName: string
+}) => (
```
Comment (wirednkod) [inline src/components/DelegationByAmountConviction.tsx:18]:
```suggestion
const TrackDisplay: React.FC<{
  trackId: number
  trackName: string
}> = ({ trackId, trackName }) => (
```

File: src/components/DelegationByAmountConviction.tsx [hunk 2]
```diff
@@ -0,0 +1,82 @@
+import { CurrentDelegation, useLocks } from '@/contexts/LocksContext'
+import { useNetwork } from '@/contexts/NetworkContext'
+import { planckToUnit } from '@polkadot-ui/utils'
+import { BadgeCent } from 'lucide-react'
+import { Badge } from './ui/badge'
+import { ContentReveal } from './ui/content-reveal'
+
+interface Props {
+  amountConvictionMap: Record<string, CurrentDelegation[]>
+}
```
Comment (wirednkod) [inline src/components/DelegationByAmountConviction.tsx:10]:
```suggestion
```

File: src/components/DelegationByAmountConviction.tsx [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+  trackName: string
+}) => (
+  <div className="capitalize" key={trackId}>
+    <Badge>{trackName}</Badge> /{trackId}
+  </div>
+)
+
+export const DelegationByAmountConviction = ({
+  amountConvictionMap,
+}: Props) => {
```
Comment (wirednkod) [inline src/components/DelegationByAmountConviction.tsx:26]:
```suggestion
export const DelegationByAmountConviction: React.FC<{
  amountConvictionMap: Record<string, CurrentDelegation[]>
}> = ({ amountConvictionMap }) => {
```

File: src/components/DelegationByAmountConviction.tsx [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+  const { trackList, assetInfo } = useNetwork()
+  const { getConvictionLockTimeDisplay } = useLocks()
+
+  return Object.values(amountConvictionMap).map((sameAcountConvictionArray) => {
```
Comment (wirednkod) [inline src/components/DelegationByAmountConviction.tsx:30]:
```suggestion
  return Object.values(amountConvictionMap).map(
    (sameAcountConvictionArray: CurrentDelegation[]) => {
```

**Review by wirednkod — APPROVED** [review]
nits

File: src/components/DelegationByAmountConviction.tsx (hunk 1 above)
Comment (Tbaut) [reply src/components/DelegationByAmountConviction.tsx:18]: We don't use this React.FC anywhere else and I don't really like that :D
What bothers you is the line amount?

File: src/components/DelegationByAmountConviction.tsx (hunk 3 above)
Comment (Tbaut) [reply src/components/DelegationByAmountConviction.tsx:26]: Same, I disagree there, I very much prefer having `Props`

File: src/components/DelegationByAmountConviction.tsx (hunk 4 above)
Comment (Tbaut) [reply src/components/DelegationByAmountConviction.tsx:30]: why? if it's inferred... correctly, I wouldn't bother

File: src/components/DelegationByAmountConviction.tsx (hunk 1 above)
Comment (wirednkod) [reply src/components/DelegationByAmountConviction.tsx:18]: Nothing  bothers me. Just prefare to have the "return" on the components name instead of inside the arguments parenthesis.. I just find it prettier :D Feel free to leave it as is

File: src/components/DelegationByAmountConviction.tsx (hunk 3 above)
Comment (wirednkod) [reply src/components/DelegationByAmountConviction.tsx:26]: Same as above. It is easier for me (and thats just me) to see the return props, instead of searching for a Props type (unless we have many repeated Props)... again just a coding style - nothing serious to fix. Feel free to disregard

File: src/components/DelegationByAmountConviction.tsx (hunk 1 above)
Comment (Tbaut) [reply src/components/DelegationByAmountConviction.tsx:18]: We can agree on naming the params types if you want? I'll change that.

Comment (Tbaut) [reply src/components/DelegationByAmountConviction.tsx:18]: ok based on the discussion

- no React.FC
- create a type/interface if either reused, or large amount of params (more than 2)
- create a type/interface per default for Props
